### ISSUE TITLE
Type Error in preloadRelatedData(): Argument #1 ($page) must be of type Z3d0X\FilamentFabricator\Models\Contracts\Page, null given

### ISSUE THREAD

**Issue by alaidi** [Matildevoldsen/Wire-Content-v2#1]
When attempting to render a page block, I encountered the following error, which seems to be related to the Fabricator plugin:

#### Error Message:
```php
TypeError: Z3d0X\FilamentFabricator\PageBlocks\PageBlock::preloadRelatedData():
Argument #1 ($page) must be of type Z3d0X\FilamentFabricator\Models\Contracts\Page,
null given, called in /Users/admin/Herd/Wire-Content-v2/storage/framework/views/677f7720ad4060f7162adda865d484c0.php on line 45
```

#### Steps to Reproduce:
1. Clone the repository.
2. Update composer dependencies using:
   ```bash
   composer install
   composer update
   npm install & npm run dev
   ```
3. Remove the following configurations from `composer.json`:
   ```json
   "repositories": [
        {
            "type": "path",
            "url": "packages/wire-content",
            "options": {
                "symlink": true
            }
        }
    ],
   ```
   and
   ```json
   "matildevoldsen/wire-content": "@dev",
   ```
4. Switch the database to SQLite.
5. Add new menu and new page.
6. Attempt to render a page block.
7. I try to clear the cash but it not working.

**Comment by Matildevoldsen** [comment]
Can you please update the issue to mention what you've tried to do to resolve it? E.g., clearing cache, how to reproduce the issue, and which file you reckon is causing it?

**Comment by alaidi** [comment]
I solve it by adding `$this->` in front of page property so  it will ensure the data is correctly passed.
update the file : `vendor/z3d0x/filament-fabricator/resources/views/components/page-blocks.blade.php`
```
if (!empty($blockClass)) {
    $blockClass::preloadRelatedData($this->page, $group);
}
```
